# Generated by Django 4.2 on 2023-06-07 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno vývojáře je povinný údaj'}, help_text='Zadejte jméno vývojáře', max_length=100, verbose_name='Jméno vývojáře')),
                ('stat', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stát')),
            ],
            options={
                'verbose_name': 'Vývojář',
                'verbose_name_plural': 'Vývojáři',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno hry musí být vyplněn'}, help_text='Zadejte jméno hry', max_length=100, verbose_name='Jméno hry')),
                ('popis', models.TextField(blank=True, help_text='Vložte popis hry', verbose_name='Popis hry')),
                ('pocet_hodin', models.PositiveIntegerField(blank=True, help_text='Zadejte délu hry v hodinách (max. 500)', null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Délka hry')),
                ('rok_vydani', models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1950 - 2100)', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání')),
                ('vyvojari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.developer', verbose_name='Vývojáři')),
            ],
            options={
                'verbose_name': 'Hra',
                'verbose_name_plural': 'Hry',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název žánru', max_length=20, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Zadej text recenze', verbose_name='Text recenze')),
                ('hodnoceni', models.PositiveSmallIntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3, verbose_name='Hodnocení')),
                ('cas', models.DateTimeField(auto_now=True)),
                ('hra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.game', verbose_name='Hra')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recenzent')),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['hra', 'recenzent'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='zanry',
            field=models.ManyToManyField(to='myapp.genre'),
        ),
    ]
