# Generated by Django 4.2 on 2023-06-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='popis',
            field=models.TextField(blank=True, help_text='Vložte popis žánru', verbose_name='Popis žánru'),
        ),
    ]
