# Generated by Django 4.2 on 2023-06-21 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_genre_popis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['jmeno'], 'verbose_name': 'Vývojář', 'verbose_name_plural': 'Vývojář'},
        ),
        migrations.AlterField(
            model_name='game',
            name='pocet_hodin',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte délku hry v hodinách (max. 500)', null=True, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Délka hry'),
        ),
    ]
