# Generated by Django 4.2 on 2023-06-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_game_zanry_game_zanry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vyvojari',
        ),
        migrations.RemoveField(
            model_name='game',
            name='zanry',
        ),
        migrations.AddField(
            model_name='game',
            name='vyvojari',
            field=models.ManyToManyField(to='myapp.developer', verbose_name='Vývojáři'),
        ),
        migrations.AddField(
            model_name='game',
            name='zanry',
            field=models.ManyToManyField(to='myapp.genre', verbose_name='Žánry'),
        ),
    ]
